import { BlockDefinition } from "@viwo/web-editor";

export const mockOpcodes: BlockDefinition[] = [
  {
    opcode: "seq",
    label: "Sequence",
    category: "control",
    type: "statement",
    layout: "vertical",
    slots: [],
  },
  {
    opcode: "print",
    label: "Print",
    category: "io",
    type: "statement",
    slots: [{ name: "message", type: "string", default: "Hello World" }],
  },
  {
    opcode: "if",
    label: "If",
    category: "control",
    type: "statement",
    layout: "control-flow",
    slots: [
      { name: "condition", type: "boolean", default: true },
      { name: "then", type: "statement", default: ["seq"] },
    ],
  },
  {
    opcode: "add",
    label: "+",
    category: "math",
    type: "number",
    layout: "infix",
    slots: [
      { name: "a", type: "number", default: 0 },
      { name: "b", type: "number", default: 0 },
    ],
  },
  {
    opcode: "sub",
    label: "-",
    category: "math",
    type: "number",
    layout: "infix",
    slots: [
      { name: "a", type: "number", default: 0 },
      { name: "b", type: "number", default: 0 },
    ],
  },
  {
    opcode: "mul",
    label: "*",
    category: "math",
    type: "number",
    layout: "infix",
    slots: [
      { name: "a", type: "number", default: 0 },
      { name: "b", type: "number", default: 0 },
    ],
  },
  {
    opcode: "div",
    label: "/",
    category: "math",
    type: "number",
    layout: "infix",
    slots: [
      { name: "a", type: "number", default: 0 },
      { name: "b", type: "number", default: 0 },
    ],
  },
  {
    opcode: "eq",
    label: "==",
    category: "logic",
    type: "boolean",
    layout: "infix",
    slots: [
      { name: "a", type: "any", default: 0 },
      { name: "b", type: "any", default: 0 },
    ],
  },
  {
    opcode: "lt",
    label: "<",
    category: "logic",
    type: "boolean",
    layout: "infix",
    slots: [
      { name: "a", type: "number", default: 0 },
      { name: "b", type: "number", default: 0 },
    ],
  },
  {
    opcode: "gt",
    label: ">",
    category: "logic",
    type: "boolean",
    layout: "infix",
    slots: [
      { name: "a", type: "number", default: 0 },
      { name: "b", type: "number", default: 0 },
    ],
  },
  {
    opcode: "and",
    label: "&&",
    category: "logic",
    type: "boolean",
    layout: "infix",
    slots: [
      { name: "a", type: "boolean", default: true },
      { name: "b", type: "boolean", default: true },
    ],
  },
  {
    opcode: "or",
    label: "||",
    category: "logic",
    type: "boolean",
    layout: "infix",
    slots: [
      { name: "a", type: "boolean", default: true },
      { name: "b", type: "boolean", default: true },
    ],
  },
  {
    opcode: "not",
    label: "!",
    category: "logic",
    type: "boolean",
    slots: [{ name: "a", type: "boolean", default: true }],
  },
  {
    opcode: "set",
    label: "Set Variable",
    category: "data",
    type: "statement",
    slots: [
      { name: "name", type: "string", default: "x" },
      { name: "value", type: "any", default: 0 },
    ],
  },
  {
    opcode: "get",
    label: "Get Variable",
    category: "data",
    type: "any",
    slots: [{ name: "name", type: "string", default: "x" }],
  },
  {
    opcode: "loop",
    label: "Loop",
    category: "control",
    type: "statement",
    layout: "control-flow",
    slots: [
      { name: "count", type: "number", default: 10 },
      { name: "body", type: "statement", default: ["seq"] },
    ],
  },
  {
    opcode: "boolean",
    label: "Boolean",
    category: "data",
    type: "boolean",
    layout: "primitive",
    slots: [{ name: "value", type: "boolean", default: false }],
  },
  {
    opcode: "number",
    label: "Number",
    category: "data",
    type: "number",
    layout: "primitive",
    slots: [{ name: "value", type: "number", default: 0 }],
  },
  {
    opcode: "string",
    label: "String",
    category: "data",
    type: "string",
    layout: "primitive",
    slots: [{ name: "value", type: "string", default: "" }],
  },
];
